name: Deploy dustinvorac.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-duration-seconds: 600
      - name: yarn
        run: yarn --frozen-lockfile
      - name: build
        run: npm run build
      - name: s3 sync
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET }}
      - name: cloudfront invalidate
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"