name: dustinvorac.com

on:
  push:
    paths-ignore:
      - "infra/**"
    branches:
      - main

env:
  region: ${{ secrets.AWS_REGION }}
  role: ${{ secrets.AWS_IAM_ROLE }}
  domain: ${{ secrets.AWS_DOMAIN }}
  cloudfront: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ env.role }}
          role-duration-seconds: 900

      - name: yarn
        run: yarn --frozen-lockfile

      - name: build
        run: yarn run build

      - name: s3 sync
        run: aws s3 sync ./dist/ s3://www.${{ env.domain }}
        
      - name: cloudfront invalidate
        run: aws cloudfront create-invalidation --distribution-id ${{ env.cloudfront }} --paths "/*"